
DROP TABLE IF EXISTS R_User_Role;
DROP TABLE IF EXISTS User;
DROP TABLE IF EXISTS Role;

CREATE TABLE User (
ID INTEGER AUTO_INCREMENT PRIMARY KEY ,
NAME VARCHAR(50),
);

CREATE TABLE Role (
ID INTEGER AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR (50)
);

CREATE TABLE R_User_Role (
USER_ID INTEGER,
ROLE_ID INTEGER
);

INSERT INTO Role (ID, NAME) VALUES (1, 'Role 1');
INSERT INTO Role (ID, NAME) VALUES (2, 'Role 2');
INSERT INTO Role (ID, NAME) VALUES (3, 'Role 3');

INSERT INTO User (ID, NAME) VALUES (1, 'Libri'); 
INSERT INTO User (ID, NAME) VALUES (2, 'BKV'); 
INSERT INTO User (ID, NAME) VALUES (3, 'Unknown Service Provider'); 

INSERT INTO R_User_Role (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO R_User_Role (USER_ID, ROLE_ID) VALUES (1, 2);
INSERT INTO R_User_Role (USER_ID, ROLE_ID) VALUES (2, 1);
INSERT INTO R_User_Role (USER_ID, ROLE_ID) VALUES (2, 3);
INSERT INTO R_User_Role (USER_ID, ROLE_ID) VALUES (3, 3);
